alter table public.evidence add column if not exists dataset_id text, add column if not exists fact_type text, add column if not exists observed_at timestamptz not null default now(), add column if not exists matched_terms jsonb not null default '[]'::jsonb, add column if not exists confidence numeric;
create index if not exists evidence_entity_idx on public.evidence(entity_type, entity_key);
create index if not exists evidence_source_dataset_idx on public.evidence(source_type, dataset_id, observed_at desc);
create unique index if not exists evidence_dedupe_idx on public.evidence(entity_type, entity_key, source_type, coalesce(external_id,''));
create index if not exists companies_uniform_idx on public.companies(uniform_number);
create index if not exists people_normalized_name_idx on public.people(normalized_name);
create table if not exists public.source_runs (
  id bigint generated by default as identity primary key,
  source_type text not null,
  dataset_id text,
  status text not null default 'running' check (status in ('running','ok','partial','failed','retired')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  records_fetched integer not null default 0,
  records_matched integer not null default 0,
  error_message text,
  source_url text,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists source_runs_latest_idx on public.source_runs(source_type, dataset_id, started_at desc);
alter table public.source_runs enable row level security;;
