create extension if not exists pg_trgm;

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  uniform_number text not null unique,
  name text,
  status text,
  representative_name text,
  address text,
  capital_amount numeric,
  established_date date,
  source text not null default 'MOEA/GCI',
  source_url text,
  fetched_at timestamptz not null default now(),
  raw_ref text
);
create index if not exists companies_name_trgm_idx on public.companies using gin (name gin_trgm_ops);

create table if not exists public.people (
  id bigint generated by default as identity primary key,
  name text not null,
  normalized_name text generated always as (lower(regexp_replace(name, '\s+', '', 'g'))) stored,
  source text not null default 'MOEA/GCI',
  fetched_at timestamptz not null default now()
);
create index if not exists people_name_trgm_idx on public.people using gin (name gin_trgm_ops);

create table if not exists public.company_people (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  person_id bigint not null references public.people(id) on delete cascade,
  role text,
  representative_entity text,
  share_count numeric,
  source text not null default 'MOEA/GCI',
  source_url text,
  fetched_at timestamptz not null default now(),
  unique(company_id, person_id, role)
);
create index if not exists company_people_company_idx on public.company_people(company_id);
create index if not exists company_people_person_idx on public.company_people(person_id);

create table if not exists public.evidence (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_key text not null,
  source_type text not null,
  title text,
  summary text,
  source_url text,
  external_id text,
  event_date date,
  severity text,
  raw_ref text,
  created_at timestamptz not null default now(),
  unique(entity_type, entity_key, source_type, external_id)
);
create index if not exists evidence_entity_idx on public.evidence(entity_type, entity_key);
create index if not exists evidence_date_idx on public.evidence(event_date desc);

create table if not exists public.api_cache (
  cache_key text primary key,
  source text not null,
  payload jsonb not null,
  fetched_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists api_cache_expiry_idx on public.api_cache(expires_at);

alter table public.companies enable row level security;
alter table public.people enable row level security;
alter table public.company_people enable row level security;
alter table public.evidence enable row level security;
alter table public.api_cache enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='companies' and policyname='companies_public_read') then
    create policy companies_public_read on public.companies for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='people' and policyname='people_public_read') then
    create policy people_public_read on public.people for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='company_people' and policyname='company_people_public_read') then
    create policy company_people_public_read on public.company_people for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='evidence' and policyname='evidence_public_read') then
    create policy evidence_public_read on public.evidence for select using (true);
  end if;
end $$;;
